import React from 'react';
import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import Header from '@/components/Header';
import ContextProvider from '../../../providers/ContextProvider';
import { Toaster } from "react-hot-toast";

const nunito = Nunito({ 
    subsets: ["latin"],
    weight: ["300", "400", "500", "600", "700"],
    variable: "--font-nunito",
  });
  
  export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
  };

export default function HomeLayout({
    children,
  }: Readonly<{
    children: React.ReactNode;
  }>) {
  return (
    <>
        <Toaster position="top-center" />
        <Header />
        <main className="py-0  w-full mx-auto h-full">
          {children}
        </main>
    </>
  )
}
